resources:
  - url: http://127.0.0.1:5000/nexxtbus-card.js
    type: module
views:
  - cards:
      - type: custom:nextbus-card
        name: NextBus Card Development
        entities:
          - sensor.sf_muni_j
          - sensor.sf_muni_n
